# Generated by Django 5.1.4 on 2024-12-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
